LizardByte/support-bot

discord_bot.py

- Fix default env variables (allows running without having these in env file or secrets)

Fix default env variables

---

.github/workflows/CI.yml

Fix Build and Push

---

.github/workflows/CI.yml

Fix permissions

---

.github/workflows/CI.yml
Dockerfile

- Fix permission issue in workflow and Release v0.0.2

Release v0.0.2

---

CHANGELOG.md
Dockerfile
README.md
discord_bot.py
sample.env

- Environment variables to uppercase

Environment variables to uppercase

---

.github/workflows/CI.yml
CHANGELOG.md
DOCKER_README.md

- Add docker readme
- Update CI for docker build
- Setup changelog for v0.0.4
- Fixes #41

Fixes for docker

---

discord_bot.py

Fix environment variable for daily release task
- Fixes #39

Fix environment variable for daily release task

---

.docker_platforms
.github/workflows/CI.yml
.github/workflows/ci-docker.yml

- refactor workflows as required by https://github.com/LizardByte/.github/pull/37
- replaces #47

refactor workflows

---

.github/workflows/CI.yml

update action location

---

.github/workflows/CI.yml

GITHUB_TOKEN is not allowed to create a release when tag protection is enabled. This PR changes the token used for creating a release.

Use personal token for release action

---

CHANGELOG.md

v0.0.5 prep

---

DOCKER_README.md

- Add `READTHEDOCS_TOKEN` to docker readme

Add `READTHEDOCS_TOKEN`

---

DOCKER_README.md
README.md
discord_bot.py
requirements.txt

- add select menus for docs command
- remove readthedocs token
- update docstrings and typehints

add select menus for docs command

---

.gitignore
discord_bot.py

remove guild file

---

.github/workflows/CI.yml

fix ci yaml-lint

---

.github/workflows/ci-docker.yml
CHANGELOG.md

update changelog for v0.1.0

---

Dockerfile

add `WORKDIR`

---

discord_avatar.py
discord_bot.py
discord_constants.py
discord_modals.py
discord_views.py

- enable timeout callback for `/docs` command after 45s
- incomplete `/docs` commands are deleted 30s after the timeout period
- `/docs` command is reset for each call
- fix url returned for `/docs` command when `None` was selected as category
- add `discord_modals.py`
- move constants to `discord_constants.py`
- move avatar related items to `discord_avatar.py`
- Fixes #105 
- Fixes #106

general enhancements

---

CHANGELOG.md
requirements.txt

- update changelog for v0.1.1
- fix dependencies for `requirements.txt`

v0.1.1 changelog

---

CHANGELOG.md

Update changelog for v0.1.2 release.

changelog: v0.1.2

---

README.md
discord_bot.py

Add `channel` command to make it easier to move discussions to another channel.
Since discord now hides the name of channels that users do not have access to, this command will make it easier for those users to get access or customize the community.

feat(commands): add `channel` command

---

.docker_platforms
.dockerignore
Dockerfile

- Update docker platforms
- Add `.dockerignore` file
- Remove unnecessary `mkdir` command

build(docker): update docker platforms

---

CHANGELOG.md

docs(changelog): bump version to 0.1.3

---

.github/workflows/ci-docker.yml
.github/workflows/ci.yml

chore: update LizardByte actions

---

src/common.py

The persistent directory was incorrect after #266.

fix: use correct data directory on docker installs

---

.github/workflows/ci.yml

ci: bump python to 3.12

---

src/discord/views.py

No longer accepting donations through meee6.

chore: remove mee6

---

.github/workflows/ci.yml

`setup-release-action` needs write permission.

ci(release): fix permissions
